"""Generate ui_mp/cod1x_files.menu — flat dark style (the validated look).

Layout: 520x328 panel, header tabs SETTINGS|FILES, two columns (CONFIGS | DEMOS)
of 10 slots each, footer SAVE AS + SAVE / REFRESH / CLOSE. Slots are driven by the
mod-published cvars (cod1x_cfg_* / cod1x_demo_*), hidden when empty.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "ui_mp", "cod1x_files.menu")

T = "\t"


def slot_lines():
    out = []
    for col, cvarp, x, w in (("c", "cod1x_cfg", 16, 240), ("d", "cod1x_demo", 276, 228)):
        for i in range(1, 11):
            y = 70 + (i - 1) * 21
            name = f"{col}{i}"
            cvar = f"{cvarp}_{i}"
            vstr = f"vstr {cvarp}_exec_{i}"
            out.append(
                f'{T}{T}itemDef {{ name {name} type ITEM_TYPE_BUTTON rect {x} {y} {w} 18 '
                f'style WINDOW_STYLE_FILLED backcolor BAT_ROW visible 1 '
                f'cvarTest "{cvar}" hideCvar {{ "" }} '
                f'mouseEnter {{ play "mouse_over"; setitemcolor {name} backcolor BAT_ROW_HOV }} '
                f'mouseExit {{ setitemcolor {name} backcolor BAT_ROW }} '
                f'action {{ play "mouse_click"; exec "{vstr}" }} }}')
            out.append(
                f'{T}{T}itemDef {{ name {name}t type ITEM_TYPE_TEXT cvar "{cvar}" '
                f'rect {x + 6} {y} {w - 10} 18 textalign ITEM_ALIGN_LEFT textalignx 0 '
                f'textaligny 13 textscale .19 textfont UI_FONT_NORMAL forecolor BAT_TEXT '
                f'visible 1 decoration cvarTest "{cvar}" hideCvar {{ "" }} }}')
    return "\n".join(out)


def text_item(name, text, rect, alignx, aligny, scale, color, shadowed=True, center=False):
    lines = [
        f"{T}{T}itemDef",
        f"{T}{T}{{",
        f"{T}{T}{T}name{T}{T}{name}",
        f"{T}{T}{T}type{T}{T}ITEM_TYPE_TEXT",
        f'{T}{T}{T}text{T}{T}"{text}"',
        f"{T}{T}{T}rect{T}{T}{rect}",
        f"{T}{T}{T}textalign{T}{'ITEM_ALIGN_CENTER' if center else 'ITEM_ALIGN_LEFT'}",
        f"{T}{T}{T}textalignx{T}{alignx}",
        f"{T}{T}{T}textaligny{T}{aligny}",
        f"{T}{T}{T}textscale{T}{scale}",
    ]
    if shadowed:
        lines.append(f"{T}{T}{T}textstyle{T}ITEM_TEXTSTYLE_SHADOWED")
    lines += [
        f"{T}{T}{T}textfont{T}UI_FONT_NORMAL",
        f"{T}{T}{T}forecolor{T}{color}",
        f"{T}{T}{T}visible{T}{T}1",
        f"{T}{T}{T}decoration",
        f"{T}{T}}}",
    ]
    return "\n".join(lines)


def button(name, text, rect, alignx, action):
    return "\n".join([
        f"{T}{T}itemDef",
        f"{T}{T}{{",
        f"{T}{T}{T}name{T}{T}{name}",
        f"{T}{T}{T}type{T}{T}ITEM_TYPE_BUTTON",
        f'{T}{T}{T}text{T}{T}"{text}"',
        f"{T}{T}{T}style{T}{T}1",
        f"{T}{T}{T}border{T}{T}1",
        f"{T}{T}{T}textstyle{T}3",
        f"{T}{T}{T}rect{T}{T}{rect}",
        f"{T}{T}{T}textalign{T}ITEM_ALIGN_CENTER",
        f"{T}{T}{T}textalignx{T}{alignx}",
        f"{T}{T}{T}textaligny{T}16",
        f"{T}{T}{T}textscale{T}.21",
        f"{T}{T}{T}textfont{T}UI_FONT_NORMAL",
        f"{T}{T}{T}forecolor{T}BAT_TEXT",
        f"{T}{T}{T}backcolor{T}BAT_BTN",
        f"{T}{T}{T}bordercolor{T}BAT_BORDER",
        f"{T}{T}{T}visible{T}{T}1",
        f'{T}{T}{T}mouseEnter{T}{{ play "mouse_over"; setitemcolor {name} backcolor BAT_BTN_HOV }}',
        f"{T}{T}{T}mouseExit{T}{{ setitemcolor {name} backcolor BAT_BTN }}",
        f"{T}{T}{T}action{T}{T}{{ {action} }}",
        f"{T}{T}}}",
    ])


HEADER = """#include "ui/menudef.h"
// COD1.6X FILES page - config loader + demo loader (flat dark style, tab of cod1x_settings).
// The menu engine cannot list files; the mod (mss32.dll) scans Main/*.cfg, Main/configs/*.cfg
// and Main/demos/*.dm_* and publishes fixed slots:
//   cod1x_cfg_1..10  display name   cod1x_cfg_exec_1..10  "exec <path>"
//   cod1x_demo_1..10 display name   cod1x_demo_exec_1..10 "demo <file>"  (newest first)
// A slot click runs `vstr` on its exec cvar. Empty slots are hidden (cvarTest/hideCvar).
// SAVE AS: cod1x_savename + cod1x_files_save=1 -> mod runs writeconfig configs/<name>.cfg.
// REFRESH / page open: cod1x_files_scan=1 -> mod rescans.
// Generated by gen_files_menu.py - edit that script, not this file.

#define BAT_BG\t\t\t.05 .06 .08 .96
#define BAT_BORDER\t\t.16 .18 .22 .8
#define BAT_ROW\t\t\t.10 .12 .15 .90
#define BAT_ROW_HOV\t\t.16 .19 .24 .95
#define BAT_ORANGE\t\t.98 .55 .10 1
#define BAT_TEXT\t\t.93 .94 .96 1
#define BAT_DIM\t\t\t.52 .55 .60 1
#define BAT_LINE\t\t.22 .24 .29 .55
#define BAT_BTN\t\t\t.12 .14 .18 .92
#define BAT_BTN_HOV\t\t.98 .55 .10 .92
"""

parts = [HEADER]
parts.append("""
{
\tmenuDef
\t{
\t\tname\t\tcod1x_files
\t\tfullScreen\t0
\t\trect\t\t60 76 520 328
\t\tfocusColor\t.98 .60 .15 1
\t\tstyle\t\tWINDOW_STYLE_EMPTY
\t\tonOpen\t\t{ setcvar cod1x_menu_open "1" ; setcvar cod1x_files_scan "1" }
\t\tonClose\t\t{ setcvar cod1x_menu_open "0" }
\t\tonESC\t\t{ close cod1x_files }

\t\titemDef { name panel_shadow rect 6 7 520 328 style WINDOW_STYLE_FILLED backcolor 0 0 0 .5 visible 1 decoration }
\t\titemDef { name panel_body rect 0 0 520 328 style WINDOW_STYLE_FILLED backcolor BAT_BG border 1 bordercolor BAT_BORDER visible 1 decoration }
\t\titemDef { name panel_edge rect 0 0 3 328 style WINDOW_STYLE_FILLED backcolor BAT_ORANGE visible 1 decoration }

\t\titemDef { name title_tick rect 16 13 3 18 style WINDOW_STYLE_FILLED backcolor BAT_ORANGE visible 1 decoration }
""")
parts.append(text_item("title", "COD 1.6X", "26 8 200 30", 0, 24, ".40", "BAT_TEXT"))
# Standalone menu (opened from the MAIN MENU "1.6X DEMOS" button). No SETTINGS tab:
# it is no longer a sub-page of the settings panel.
parts.append(text_item("tab_files", "FILES", "434 12 70 22", 35, 16, ".21", "BAT_ORANGE", center=True))
parts.append("""\t\titemDef { name tab_files_bar rect 434 34 70 2 style WINDOW_STYLE_FILLED backcolor BAT_ORANGE visible 1 decoration }

\t\titemDef { name header_line rect 12 44 496 1 style WINDOW_STYLE_FILLED backcolor BAT_LINE visible 1 decoration }
""")
parts.append(text_item("section_configs", "CONFIGS", "16 50 200 14", 0, 11, ".20", "BAT_ORANGE"))
parts.append("\t\titemDef { name section_configs_line rect 92 56 164 1 style WINDOW_STYLE_FILLED backcolor BAT_LINE visible 1 decoration }\n")
parts.append(text_item("section_demos", "DEMOS", "276 50 200 14", 0, 11, ".20", "BAT_ORANGE"))
parts.append("\t\titemDef { name section_demos_line rect 340 56 164 1 style WINDOW_STYLE_FILLED backcolor BAT_LINE visible 1 decoration }\n")
parts.append("\t\titemDef { name col_split rect 266 64 1 216 style WINDOW_STYLE_FILLED backcolor BAT_LINE visible 1 decoration }\n")
parts.append(slot_lines())
parts.append("""
\t\titemDef { name footer_line rect 12 288 496 1 style WINDOW_STYLE_FILLED backcolor BAT_LINE visible 1 decoration }
""")
parts.append(text_item("save_label", "SAVE AS", "16 296 60 24", 0, 16, ".19", "BAT_DIM"))
parts.append("""
\t\titemDef
\t\t{
\t\t\tname\t\tsave_name
\t\t\ttype\t\tITEM_TYPE_EDITFIELD
\t\t\tcvar\t\t"cod1x_savename"
\t\t\tmaxChars\t24
\t\t\tmaxpaintchars\t16
\t\t\trect\t\t78 297 116 20
\t\t\ttextalign\tITEM_ALIGN_LEFT
\t\t\ttextalignx\t4
\t\t\ttextaligny\t14
\t\t\ttextscale\t.20
\t\t\ttextfont\tUI_FONT_NORMAL
\t\t\tstyle\t\tWINDOW_STYLE_FILLED
\t\t\tbackcolor\tBAT_ROW
\t\t\tbordercolor\tBAT_BORDER
\t\t\tborder\t\t1
\t\t\tforecolor\tBAT_TEXT
\t\t\tvisible\t\t1
\t\t\tmouseEnter\t{ play "mouse_over"; }
\t\t}
""")
parts.append(button("savebtn", "SAVE", "200 296 56 22", 28, 'play "mouse_click"; setcvar cod1x_files_save "1"'))
parts.append("")
parts.append(button("refreshbtn", "REFRESH", "356 296 70 22", 35, 'play "mouse_click"; setcvar cod1x_files_scan "1"'))
parts.append("")
parts.append(button("closebtn", "CLOSE", "434 296 70 22", 35, 'play "mouse_click"; close cod1x_files'))
parts.append("\t}\n}\n")

menu = "\n".join(parts)
open(OUT, "w", encoding="latin1", newline="\n").write(menu)
o, c = menu.count("{"), menu.count("}")
print("written", OUT)
print("braces", o, c, "OK" if o == c else "MISMATCH")
