// CoD1 is Vert- on non-4:3. Hor+ FOV correction via CG_GetEffectiveFov hook,
// plus custom resolution/refresh through a generated autoexec.cfg.

#include "video/widescreen_fix.h"
#include "video/window_patch.h"
#include "core/logger.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <cmath>

namespace patches {

// must be external: only read from trampoline asm, -O2 would drop it otherwise
extern "C" { void* g_calcfov_original = nullptr; }

WidescreenConfig g_widescreen_config = {
    /* horplus_fov_enable    */ true,
    /* aspect_mode           */ AspectMode::Auto,
    /* custom_ratio          */ 1.778f,
    /* horplus_hook_caller2  */ true,
    /* force_resolution      */ false,
    /* width                 */ 1920,
    /* height                */ 1080,
    /* refresh_hz            */ 0,
};

namespace {

constexpr float kPi = 3.14159265358979323846f;

float detect_monitor_aspect() {
    const int cx = GetSystemMetrics(SM_CXSCREEN);
    const int cy = GetSystemMetrics(SM_CYSCREEN);
    if (cy <= 0) return 1.778f;
    return (float)cx / (float)cy;
}

// viewport (not monitor) aspect drives Hor+: a 4:3 r_mode on a 16:9 monitor
// must use the 4:3 frame aspect, else hfov is over-corrected
float detect_viewport_aspect() {
    HWND hwnd = get_game_window();
    if (hwnd) {
        RECT rc;
        if (GetClientRect(hwnd, &rc)) {
            const int w = rc.right - rc.left;
            const int h = rc.bottom - rc.top;
            if (h > 0 && w > 0) return (float)w / (float)h;
        }
    }
    return detect_monitor_aspect();
}

float aspect_for_mode(AspectMode m, float custom) {
    switch (m) {
        case AspectMode::Auto:    return detect_viewport_aspect();
        case AspectMode::R_4_3:   return 4.0f / 3.0f;
        case AspectMode::R_16_9:  return 16.0f / 9.0f;
        case AspectMode::R_16_10: return 16.0f / 10.0f;
        case AspectMode::R_21_9:  return 64.0f / 27.0f;
        case AspectMode::Custom:  return custom > 0.1f ? custom : 1.778f;
    }
    return 1.778f;
}

const char* aspect_mode_name(AspectMode m) {
    switch (m) {
        case AspectMode::Auto:    return "auto";
        case AspectMode::R_4_3:   return "4:3";
        case AspectMode::R_16_9:  return "16:9";
        case AspectMode::R_16_10: return "16:10";
        case AspectMode::R_21_9:  return "21:9";
        case AspectMode::Custom:  return "custom";
    }
    return "?";
}

// <CoD1>/main/ relative to CoDMP.exe
bool get_main_dir(char* out, size_t out_size) {
    char exe_path[MAX_PATH];
    DWORD len = GetModuleFileNameA(NULL, exe_path, MAX_PATH);
    if (len == 0 || len == MAX_PATH) return false;

    char* slash = strrchr(exe_path, '\\');
    if (!slash) return false;
    *(slash + 1) = '\0';

    int written = snprintf(out, out_size, "%smain\\", exe_path);
    return written > 0 && (size_t)written < out_size;
}

// regenerated each launch from the .ini; no-op file when all options off
void write_autoexec_cfg() {
    char main_dir[MAX_PATH];
    if (!get_main_dir(main_dir, sizeof(main_dir))) {
        logger::logf("widescreen: cannot locate main/ folder");
        return;
    }

    char cfg_path[MAX_PATH];
    snprintf(cfg_path, sizeof(cfg_path), "%scod1reloaded_autoexec.cfg", main_dir);

    FILE* f = fopen(cfg_path, "w");
    if (!f) {
        logger::logf("widescreen: cannot open %s for write (err=%lu)",
                     cfg_path, GetLastError());
        return;
    }

    fprintf(f, "// auto-generated by cod1reloaded.dll - DO NOT EDIT\n");
    fprintf(f, "// to take effect, add this line to your config_mp.cfg:\n");
    fprintf(f, "//   exec cod1reloaded_autoexec.cfg\n");
    fprintf(f, "// this file is REWRITTEN on every game launch from\n");
    fprintf(f, "// cod1reloaded.ini - don't edit it, edit the .ini instead.\n\n");

    const bool want_res     = g_widescreen_config.force_resolution &&
                              g_widescreen_config.width  > 0 &&
                              g_widescreen_config.height > 0;
    const bool want_refresh = g_widescreen_config.refresh_hz > 0;

    if (!want_res && !want_refresh) {
        fprintf(f, "// (no-op: widescreen_force_resolution=false in cod1reloaded.ini)\n");
        fprintf(f, "// remove this file to clean up, or re-enable in the .ini.\n");
        fclose(f);
        logger::logf("widescreen: wrote no-op autoexec to %s "
                     "(force_resolution=false, refresh=0)", cfg_path);
        return;
    }

    if (want_res) {
        fprintf(f, "seta r_mode \"-1\"\n");
        fprintf(f, "seta r_customwidth \"%d\"\n",  g_widescreen_config.width);
        fprintf(f, "seta r_customheight \"%d\"\n", g_widescreen_config.height);
        fprintf(f, "seta r_aspectratio \"%g\"\n",
                widescreen_get_aspect_ratio());
    }

    if (want_refresh) {
        fprintf(f, "seta r_displayrefresh \"%d\"\n",
                g_widescreen_config.refresh_hz);
    }

    fprintf(f, "\nvid_restart\n");
    fclose(f);

    logger::logf("widescreen: wrote autoexec to %s", cfg_path);
}

// engine strips the exec line on shutdown (only persists seta), re-add it.
// runs in DllMain before the engine reads its config.
void ensure_exec_line_in_config_mp() {
    char main_dir[MAX_PATH];
    if (!get_main_dir(main_dir, sizeof(main_dir))) return;

    char cfg_path[MAX_PATH];
    snprintf(cfg_path, sizeof(cfg_path), "%sconfig_mp.cfg", main_dir);

    FILE* fr = fopen(cfg_path, "rb");
    bool has_line = false;
    bool ends_with_newline = true;
    if (fr) {
        fseek(fr, 0, SEEK_END);
        long sz = ftell(fr);
        fseek(fr, 0, SEEK_SET);
        if (sz > 0 && sz < 4 * 1024 * 1024) {
            char* buf = (char*)malloc((size_t)sz + 1);
            if (buf) {
                size_t n = fread(buf, 1, (size_t)sz, fr);
                buf[n] = '\0';
                has_line = (strstr(buf, "exec cod1reloaded_autoexec.cfg") != NULL);
                if (n > 0 && buf[n - 1] != '\n' && buf[n - 1] != '\r') {
                    ends_with_newline = false;
                }
                free(buf);
            }
        }
        fclose(fr);
    } else {
        ends_with_newline = true;
    }

    if (has_line) {
        logger::logf("widescreen: config_mp.cfg already has exec line, skipping");
        return;
    }

    FILE* fa = fopen(cfg_path, "ab");
    if (!fa) {
        logger::logf("widescreen: cannot append to %s (err=%lu) - "
                     "add `exec cod1reloaded_autoexec.cfg` manually",
                     cfg_path, GetLastError());
        return;
    }
    if (!ends_with_newline) fputc('\n', fa);
    fprintf(fa, "exec cod1reloaded_autoexec.cfg\n");
    fclose(fa);

    logger::logf("widescreen: appended `exec cod1reloaded_autoexec.cfg` to %s",
                 cfg_path);
}

// CG_GetEffectiveFov (fcn.300344c0): no args, returns effective hfov in ST(0),
// preserves ECX internally. Two callers (see *_CALL[12]_RVA in the header).

static float g_cached_aspect = 1.778f;

// fov_43 = vanilla effective hfov; aspect recomputed each frame to track the
// live viewport across vid_restart. <=4:3 = no-op.
extern "C" float __cdecl apply_horplus_fov(float fov_43) {
    if (!g_widescreen_config.horplus_fov_enable) return fov_43;
    const float aspect = aspect_for_mode(g_widescreen_config.aspect_mode,
                                         g_widescreen_config.custom_ratio);
    if (aspect <= 4.0f / 3.0f + 0.01f) return fov_43;
    return widescreen_horplus_hfov(fov_43, aspect);
}

// no stack args, ECX preserved, float result in ST(0)
extern "C" __attribute__((naked))
void calcfov_horplus_wrapper() {
    asm(
        "call *_g_calcfov_original\n\t"

        "pushl %ecx\n\t"  // cdecl callee may trash ECX

        "subl $4, %esp\n\t"
        "fstps (%esp)\n\t"

        "call _apply_horplus_fov\n\t"

        "addl $4, %esp\n\t"
        "popl %ecx\n\t"

        "ret\n\t"
    );
}

// rewrite a 5-byte E8+rel32 call site to our wrapper
bool patch_call_site(uintptr_t call_site, uintptr_t expected_target,
                     uintptr_t wrapper) {
    const uint8_t op = *(const uint8_t*)call_site;
    if (op != 0xE8) {
        logger::logf("widescreen: call site 0x%x opcode mismatch (0x%02x, expected E8)",
                     (unsigned)call_site, op);
        return false;
    }
    const int32_t old_off = *(const int32_t*)(call_site + 1);
    const uintptr_t old_target = call_site + 5 + (intptr_t)old_off;
    if (old_target == wrapper) return true;  // already our hook (idempotent)
    if (old_target != expected_target) {
        logger::logf("widescreen: call site 0x%x targets 0x%x but expected 0x%x",
                     (unsigned)call_site, (unsigned)old_target, (unsigned)expected_target);
        return false;
    }
    const int32_t new_off = (int32_t)(wrapper - (call_site + 5));
    DWORD old_protect = 0;
    if (!VirtualProtect((void*)(call_site + 1), 4, PAGE_READWRITE, &old_protect)) {
        return false;
    }
    *(int32_t*)(call_site + 1) = new_off;
    VirtualProtect((void*)(call_site + 1), 4, old_protect, &old_protect);
    return true;
}

bool install_horplus_hook(HMODULE cgame_module) {
    if (!g_widescreen_config.horplus_fov_enable) {
        logger::logf("widescreen: horplus hook disabled by config");
        return true;
    }
    if (!cgame_module) return false;

    const uintptr_t base    = (uintptr_t)cgame_module;
    const uintptr_t calcfov = base + CGAME_CALCFOV_RVA;
    const uintptr_t call1   = base + CGAME_CALCFOV_CALL1_RVA;
    const uintptr_t call2   = base + CGAME_CALCFOV_CALL2_RVA;
    const uintptr_t wrapper = (uintptr_t)&calcfov_horplus_wrapper;

    g_calcfov_original = (void*)calcfov;

    // call1 = render path (CG_CalcViewValues tail); this is what makes Hor+ visible
    bool ok1 = patch_call_site(call1, calcfov, wrapper);
    if (!ok1) {
        logger::logf("widescreen: horplus hook FAILED on render call site");
        return false;
    }

    // call2 = CG_DrawSkyBoxPortal; same math, hook it or the sky horizon won't match
    bool ok2 = false;
    if (g_widescreen_config.horplus_hook_caller2) {
        ok2 = patch_call_site(call2, calcfov, wrapper);
        if (!ok2) {
            logger::logf("widescreen: horplus hook FAILED on secondary call site");
        }
    }

    logger::logf("widescreen: horplus hook installed render=%d secondary=%s "
                 "(trampoline 0x%08x, current aspect %.4f)",
                 ok1, (g_widescreen_config.horplus_hook_caller2
                       ? (ok2 ? "yes" : "FAILED") : "skipped"),
                 (unsigned)wrapper, g_cached_aspect);
    return ok1;
}

}  // namespace

float widescreen_get_aspect_ratio() {
    return aspect_for_mode(g_widescreen_config.aspect_mode,
                           g_widescreen_config.custom_ratio);
}

float widescreen_horplus_hfov(float cg_fov_43, float actual_aspect) {
    // vfov the 4:3 setup would have, then re-derive hfov for actual_aspect
    const float vfov_rad = 2.0f * atanf(
        (3.0f / 4.0f) * tanf(cg_fov_43 * kPi / 360.0f));

    const float hfov_rad = 2.0f * atanf(
        actual_aspect * tanf(vfov_rad / 2.0f));

    return hfov_rad * 180.0f / kPi;
}

void widescreen_fix_apply() {
    const float aspect = widescreen_get_aspect_ratio();
    g_cached_aspect = aspect;
    logger::logf("widescreen: aspect_mode=%s ratio=%.4f (monitor=%dx%d)",
                 aspect_mode_name(g_widescreen_config.aspect_mode),
                 aspect,
                 GetSystemMetrics(SM_CXSCREEN),
                 GetSystemMetrics(SM_CYSCREEN));

    if (g_widescreen_config.horplus_fov_enable) {
        const float fov80_horplus = widescreen_horplus_hfov(80.0f, aspect);
        const float fov90_horplus = widescreen_horplus_hfov(90.0f, aspect);
        logger::logf("widescreen: horplus enabled. cg_fov 80 -> effective hfov %.1f, "
                     "cg_fov 90 -> effective hfov %.1f",
                     fov80_horplus, fov90_horplus);
    }

    write_autoexec_cfg();
    ensure_exec_line_in_config_mp();
    // hook itself applied later via widescreen_apply_to_cgame() once cgame loads
}

bool widescreen_apply_to_cgame(HMODULE cgame_module) {
    return install_horplus_hook(cgame_module);
}

}  // namespace patches
