// test_ini_template.cpp - the .ini built into the DLL (build/generated/ini_template.h,
// generated by CMake from cod1reloaded.ini) is the shipped file byte for byte, and the
// lock finds nothing to change in it (so a recreated .ini never gets a second rewrite).
//   g++ -std=c++17 -O2 -I src -I build/generated tools/test_ini_template.cpp src/core/ini_lock.cpp
//       src/core/logger.cpp -o build/test_ini_template && build/test_ini_template
#include "ini_template.h"
#include "core/ini_lock.h"
#include "performance/frame_limiter.h"
#include "performance/gpu_sync.h"
#include "performance/fps_cap.h"
#include "performance/cpu_affinity.h"
#include "video/fullscreen_patch.h"
#include "features/settings_menu.h"

#include <windows.h>
#include <cstdio>
#include <cstring>
#include <string>

namespace patches {
FrameLimiterConfig  g_frame_limiter_config = { false, 0, false };
GpuSyncConfig       g_gpu_sync_config = { GPU_SYNC_OFF };
FpsCapConfig        g_fps_cap_config = { false };
CpuAffinityConfig   g_cpu_affinity_config = { 4, 0 };
FullscreenConfig    g_fullscreen_config = { true, false };
SettingsMenuConfig  g_settings_menu_config;
}  // namespace patches

using namespace patches;

static std::string slurp(const char* p) {
    FILE* f = fopen(p, "rb");
    if (!f) return "";
    std::string s; char b[4096]; size_t n;
    while ((n = fread(b, 1, sizeof(b), f)) > 0) s.append(b, n);
    fclose(f);
    return s;
}
static int g_failed = 0;
static void check(bool ok, const char* what) { printf("  [%s] %s\n", ok ? "OK" : "FAIL", what); if (!ok) ++g_failed; }

int main() {
    const std::string shipped = slurp("cod1reloaded.ini");
    check(!shipped.empty(), "cod1reloaded.ini readable (run from the repo root)");
    const std::string embedded((const char*)kIniTemplate, kIniTemplateSize);
    check(embedded == shipped, "embedded copy identical to cod1reloaded.ini");
    check(kIniTemplateSize > 4000, "embedded copy is the real file, not a stub");

    const char* tmp = "build/test_ini_template.ini";
    FILE* w = fopen(tmp, "wb");
    fwrite(kIniTemplate, 1, kIniTemplateSize, w);
    fclose(w);
    ini_lock_apply(tmp);
    check(slurp(tmp) == shipped, "the lock leaves the recreated .ini untouched (all 7 keys already in line)");
    check(g_cpu_affinity_config.cores_count == 0 && g_gpu_sync_config.mode == GPU_SYNC_AUTO &&
          g_frame_limiter_config.enable, "locked values forced");
    printf("%s\n", g_failed ? "FAILED" : "ALL OK");
    return g_failed ? 1 : 0;
}
